name: Multi-Env CI/CD

on:
    push:
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build & Push Backend
              uses: docker/build-push-action@v5
              with:
                  context: ./backend
                  tags: rasyaradja/backend:${{ github.ref_name == 'master' && 'latest' || 'staging' }}
                  push: true

            - name: Build & Push Frontend
              uses: docker/build-push-action@v5
              with:
                  context: ./frontend
                  tags: rasyaradja/frontend:${{ github.ref_name == 'master' && 'latest' || 'staging' }}
                  push: true

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Environment
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ github.ref_name == 'master' && secrets.PROD_SSH_HOST || secrets.STAGING_SSH_HOST }}
                  username: ${{ github.ref_name == 'master' && secrets.PROD_SSH_USER || secrets.STAGING_SSH_USER }}
                  key: ${{ github.ref_name == 'master' && secrets.PROD_SSH_KEY || secrets.STAGING_SSH_KEY }}
                  script: |
                      cd /home/ubuntu/reactdoc/react-express-mongodb
                      docker-compose -f docker-compose.${{ github.ref_name == 'master' && 'prod' || 'staging' }}.yml pull
                      docker-compose -f docker-compose.${{ github.ref_name == 'master' && 'prod' || 'staging' }}.yml up -d
